// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCRWx66al8vkvIYE1r8kr1qUmiVH_1cs',
    appId: '1:156714686968:web:03205aaa2b93a271e19e0d',
    messagingSenderId: '156714686968',
    projectId: 'cash-55a07',
    authDomain: 'cash-55a07.firebaseapp.com',
    storageBucket: 'cash-55a07.appspot.com',
    measurementId: 'G-32KBBLSR8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPbwGxN5nltmGTRQMGuRJvQoEv15RM6o',
    appId: '1:156714686968:android:edcd622818fff798e19e0d',
    messagingSenderId: '156714686968',
    projectId: 'cash-55a07',
    storageBucket: 'cash-55a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUmVA4tIdnBsrLZV5vTILKKADfGMqacYc',
    appId: '1:156714686968:ios:737b341f653da585e19e0d',
    messagingSenderId: '156714686968',
    projectId: 'cash-55a07',
    storageBucket: 'cash-55a07.appspot.com',
    iosClientId: '156714686968-fs9indkf40u445lc282lvlijattlcp1j.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.cash',
  );
}
